'use server';

import { createClient } from '@/lib/supabase/server';
import { createClient as createAdminClient } from '@supabase/supabase-js';

interface ActionError extends Error {
  message: string;
}

// Service Role Client for bypassing RLS
function createServiceClient() {
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!supabaseUrl || !serviceRoleKey) {
    throw new Error('Missing Supabase environment variables');
  }

  return createAdminClient(supabaseUrl, serviceRoleKey, {
    auth: {
      autoRefreshToken: false,
      persistSession: false,
    },
  });
}

// Register as Partner
export async function registerAsPartner(formData: {
  email: string;
  password: string;
  firstName: string;
  lastName: string;
  phone: string;
  businessName?: string;
}) {
  const supabase = await createClient();
  let adminClient;

  try {
    adminClient = createServiceClient();
  } catch (error) {
    console.error('[registerAsPartner] Service client error:', error);
    return { success: false, error: 'Service configuration error' };
  }

  try {
    // Validate input
    if (!formData.email || !formData.password || !formData.firstName || !formData.lastName) {
      return { success: false, error: 'Missing required fields' };
    }

    if (formData.password.length < 6) {
      return { success: false, error: 'Password must be at least 6 characters' };
    }

    console.log('[registerAsPartner] Starting registration for:', formData.email);

    // 1. Create auth user
    const { data: authData, error: authError } = await supabase.auth.signUp({
      email: formData.email.toLowerCase().trim(),
      password: formData.password,
      options: {
        data: {
          first_name: formData.firstName.trim(),
          last_name: formData.lastName.trim(),
          role: 'partner',
        },
        emailRedirectTo: `${process.env.NEXT_PUBLIC_SITE_URL}/partner/login`,
      },
    });

    if (authError) {
      console.error('[registerAsPartner] Auth error:', authError);
      
      if (authError.message.includes('already registered')) {
        return { success: false, error: 'Email already registered. Please login instead.' };
      }
      
      return { success: false, error: authError.message };
    }

    if (!authData.user) {
      return { success: false, error: 'Failed to create user account' };
    }

    const userId = authData.user.id;
    console.log('[registerAsPartner] Auth user created:', userId);

    // 2. Create profile with admin client (bypass RLS)
    // ✅ FIXED: Removed 'email' field - it doesn't exist in profiles table
    const { error: profileError } = await adminClient.from('profiles').insert({
      id: userId,
      first_name: formData.firstName.trim(),
      last_name: formData.lastName.trim(),
      role: 'partner',
      phone: formData.phone.trim(),
      email_verified: false, // Will be verified via email
    });

    if (profileError) {
      console.error('[registerAsPartner] Profile error:', profileError);
      // Clean up auth user if profile creation fails
      await adminClient.auth.admin.deleteUser(userId);
      return { success: false, error: 'Failed to create profile' };
    }

    console.log('[registerAsPartner] Profile created successfully');

    // 3. Create partner record (partner_code auto-generated by trigger)
    const { data: partner, error: partnerError } = await adminClient
      .from('partners')
      .insert({
        user_id: userId,
        business_name: formData.businessName?.trim() || null,
        phone_number: formData.phone.trim(),
        commission_rate: 15, // Default 15% for lecturer referrals
        status: 'active', // Auto-approve
        total_referrals: 0,
        active_referrals: 0,
        total_earnings: 0,
        pending_earnings: 0,
        total_withdrawn: 0,
      })
      .select('partner_code')
      .single();

    if (partnerError) {
      console.error('[registerAsPartner] Partner error:', partnerError);
      // Clean up if partner creation fails
      await adminClient.from('profiles').delete().eq('id', userId);
      await adminClient.auth.admin.deleteUser(userId);
      return { success: false, error: 'Failed to create partner account' };
    }

    if (!partner) {
      console.error('[registerAsPartner] Partner record not created');
      // Clean up
      await adminClient.from('profiles').delete().eq('id', userId);
      await adminClient.auth.admin.deleteUser(userId);
      return { success: false, error: 'Partner record creation failed' };
    }

    // 4. Wallet auto-created by database trigger
    console.log('[registerAsPartner] Success! Partner code:', partner.partner_code);

    return {
      success: true,
      message: 'Partner account created successfully!',
      data: {
        partnerCode: partner.partner_code,
        userId,
      },
    };
  } catch (error) {
    console.error('[registerAsPartner] Error:', error);
    return { success: false, error: (error as ActionError).message || 'An unexpected error occurred' };
  }
}

// Login as Partner
export async function loginAsPartner(email: string, password: string) {
  const supabase = await createClient();

  try {
    // Validate input
    if (!email || !password) {
      return { success: false, error: 'Email and password are required' };
    }

    console.log('[loginAsPartner] Attempting login for:', email);

    // Sign in with email and password
    const { data: authData, error: signInError } = await supabase.auth.signInWithPassword({
      email: email.toLowerCase().trim(),
      password,
    });

    if (signInError) {
      console.error('[loginAsPartner] Sign in error:', signInError);
      
      if (signInError.message.includes('Invalid login credentials')) {
        return { success: false, error: 'Invalid email or password' };
      }
      
      return { success: false, error: signInError.message };
    }

    if (!authData.user) {
      return { success: false, error: 'Login failed' };
    }

    console.log('[loginAsPartner] Auth successful, checking role...');

    // Verify user role
    const { data: profile, error: profileError } = await supabase
      .from('profiles')
      .select('role')
      .eq('id', authData.user.id)
      .maybeSingle();

    if (profileError) {
      console.error('[loginAsPartner] Profile error:', profileError);
      return { success: false, error: 'Failed to verify user role' };
    }

    if (!profile || profile.role !== 'partner') {
      console.log('[loginAsPartner] Wrong role:', profile?.role);
      // Sign out if not a partner
      await supabase.auth.signOut();
      return { success: false, error: 'This account is not registered as a partner' };
    }

    // Get partner details
    const { data: partnerData, error: partnerError } = await supabase
      .from('partners')
      .select('*')
      .eq('user_id', authData.user.id)
      .maybeSingle();

    if (partnerError) {
      console.error('[loginAsPartner] Partner error:', partnerError);
      return { success: false, error: 'Failed to load partner details' };
    }

    if (!partnerData) {
      return { success: false, error: 'Partner account not found' };
    }

    console.log('[loginAsPartner] Success! User:', authData.user.id);

    return {
      success: true,
      message: 'Login successful!',
      user: authData.user,
      partner: partnerData,
    };
  } catch (error) {
    console.error('[loginAsPartner] Error:', error);
    return { success: false, error: (error as ActionError).message || 'An unexpected error occurred' };
  }
}

// Check Email Availability
export async function checkEmailAvailability(email: string) {
  const supabase = await createClient();

  try {
    // Check in auth.users via RPC or by attempting signup check
    // Since we can't directly query auth.users, we check profiles
    const { data, error } = await supabase
      .from('profiles')
      .select('id')
      .ilike('first_name', email.toLowerCase()) // Workaround - need better solution
      .maybeSingle();

    if (error) {
      console.error('[checkEmailAvailability] Error:', error);
      return { success: false, available: false, error: 'Failed to check email' };
    }

    return { success: true, available: !data };
  } catch (error) {
    console.error('[checkEmailAvailability] Error:', error);
    return { success: false, available: false, error: (error as ActionError).message };
  }
}

// Get Partner Details (for logged-in partners)
export async function getPartnerDetails(userId: string) {
  const supabase = await createClient();

  try {
    const { data: partner, error } = await supabase
      .from('partners')
      .select('*, profile:profiles!user_id(first_name, last_name, phone)')
      .eq('user_id', userId)
      .maybeSingle();

    if (error) {
      console.error('[getPartnerDetails] Error:', error);
      return { success: false, error: 'Failed to load partner details', partner: null };
    }

    if (!partner) {
      return { success: false, error: 'Partner not found', partner: null };
    }

    // Get email from auth.users
    const { data: { user } } = await supabase.auth.getUser();
    
    return { 
      success: true, 
      partner: {
        ...partner,
        email: user?.email,
      }
    };
  } catch (error) {
    console.error('[getPartnerDetails] Error:', error);
    return { success: false, error: (error as ActionError).message, partner: null };
  }
}

// Update Partner Profile
export async function updatePartnerProfile(
  userId: string,
  data: {
    firstName?: string;
    lastName?: string;
    phone?: string;
    businessName?: string;
  }
) {
  let adminClient;

  try {
    adminClient = createServiceClient();
  } catch (error) {
    console.error('[updatePartnerProfile] Service client error:', error);
    return { success: false, error: 'Service configuration error' };
  }

  try {
    // Update profile
    if (data.firstName || data.lastName || data.phone) {
      const updateData: Record<string, any> = {};
      if (data.firstName) updateData.first_name = data.firstName;
      if (data.lastName) updateData.last_name = data.lastName;
      if (data.phone) updateData.phone = data.phone;

      const { error: profileError } = await adminClient
        .from('profiles')
        .update(updateData)
        .eq('id', userId);

      if (profileError) throw profileError;
    }

    // Update partner data
    if (data.businessName !== undefined || data.phone) {
      const updateData: Record<string, any> = {};
      if (data.businessName !== undefined) updateData.business_name = data.businessName;
      if (data.phone) updateData.phone_number = data.phone;

      const { error: partnerError } = await adminClient
        .from('partners')
        .update(updateData)
        .eq('user_id', userId);

      if (partnerError) throw partnerError;
    }

    return { success: true, message: 'Profile updated successfully' };
  } catch (error) {
    console.error('[updatePartnerProfile] Error:', error);
    return { success: false, error: (error as ActionError).message };
  }
}

// Get Partner Referral Stats (for dashboard)
export async function getPartnerReferralStats(userId: string) {
  const supabase = await createClient();

  try {
    const { data: partner, error } = await supabase
      .from('partners')
      .select('*')
      .eq('user_id', userId)
      .maybeSingle();

    if (error) throw error;

    if (!partner) {
      return { success: false, error: 'Partner not found' };
    }

    // Get referral earnings
    const { data: earnings, error: earningsError } = await supabase
      .from('partner_earnings')
      .select('*')
      .eq('partner_id', partner.id);

    if (earningsError) throw earningsError;

    const totalEarnings = (earnings ?? []).reduce((sum: number, e: any) => sum + (e.commission_amount ?? 0), 0);
    const paidEarnings = (earnings ?? [])
      .filter((e: any) => e.status === 'paid')
      .reduce((sum: number, e: any) => sum + (e.commission_amount ?? 0), 0);

    return {
      success: true,
      stats: {
        totalReferrals: partner.total_referrals,
        activeReferrals: partner.active_referrals,
        totalEarnings,
        pendingEarnings: totalEarnings - paidEarnings,
        paidEarnings,
        totalWithdrawn: partner.total_withdrawn,
      },
    };
  } catch (error) {
    console.error('[getPartnerReferralStats] Error:', error);
    return { success: false, error: (error as ActionError).message };
  }
}